apiVersion: v1
kind: Service
metadata:
  name: change-data-capture-hub-nodeport-service
spec:
  type: NodePort
  selector:
    app: change-data-capture-hub
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
---
apiVersion: v1
kind: Service
metadata:
  name: to-do-list-manager-nodeport-service
spec:
  type: NodePort
  selector:
    app: to-do-list-manager
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport-service
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
