apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-list-manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: to-do-list-manager
  template:
    metadata:
      labels:
        app: to-do-list-manager
    spec:
      containers:
        - name: to-do-list-manager
          image: local/to-do-list-manager-web:1.0
          resources:
            limits:
              memory: "250Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: to-do-list-manager-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: to-do-list-manager
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: rm-grpc
      protocol: TCP
      port: 666
      targetPort: 666
