apiVersion: apps/v1
kind: Deployment
metadata:
  name: change-data-capture-hub-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: change-data-capture-hub
  template:
    metadata:
      labels:
        app: change-data-capture-hub
    spec:
      containers:
        - name: change-data-capture-hub
          image: <-- ChangeDataCaptureHub Application Docker Image Name with Tag -->
          resources:
            limits:
              memory: "250Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: change-data-capture-hub-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: change-data-capture-hub
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
