apiVersion: apps/v1
kind: Deployment
metadata:
  name: change-data-capture-hub-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: change-data-capture-hub
  template:
    metadata:
      labels:
        app: change-data-capture-hub
    spec:
      containers:
        - name: change-data-capture-hub
          image: local/change-data-capture-hub-web:1.0.0
          resources:
            limits:
              memory: "250Mi"
              cpu: "500m"
          env:
            - name: AllowedHosts
              value: "*"
            - name: Logging__LogLevel__Default
              value: "Warning"
            - name: Logging__LogLevel__Microsoft.AspNetCore
              value: "Warning"
            - name: MongoDb__ConnectionString
              value: "mongodb://mongodb-clusterip-service:27017"
            - name: MongoDb__DatabaseName
              value: "ChangeDataCaptureHub"
            - name: MongoDb__CollectionName
              value: "ToDoItems"
            - name: RabbitMqConfiguration__Host
              value: "rabbitmq-clusterip-service"
            - name: RabbitMqConfiguration__Port
              value: "5672"
            - name: RabbitMqConfiguration__TriggerExchangeName
              value: "trigger"
            - name: RabbitMqConfiguration__TriggerQueueName
              value: "trigger"
            - name: ToDoListManagerGrpc
              value: "http://to-do-list-manager-clusterip-service:666"
            - name: ToDoListManagerRestBaseAddress
              value: "http://to-do-list-manager-clusterip-service:80/api"
---
apiVersion: v1
kind: Service
metadata:
  name: change-data-capture-hub-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: change-data-capture-hub
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
